<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.GuardKit\StruttonTechnologies.Core.ToolKit.Guardkit.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.Registration\StruttonTechnologies.Core.ToolKit.Registration.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.TestingKit\StruttonTechnologies.Core.Toolkit.TestingKit.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.TestingKit.Assertions\StruttonTechnologies.Core.ToolKit.TestingKit.Assertions.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.TestingKit.AspNetCore\StruttonTechnologies.Core.ToolKit.TestingKit.AspNetCore.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.TestingKit.EntityFramework\StruttonTechnologies.Core.ToolKit.TestingKit.EntityFramework.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.TestingKit.Logging\StruttonTechnologies.Core.ToolKit.TestingKit.Logging.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.Exceptions\StruttonTechnologies.Core.ToolKit.Exceptions.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.Time\StruttonTechnologies.Core.ToolKit.Time.csproj" />
    <ProjectReference Include="..\StruttonTechnologies.Core.ToolKit.TestingKit.Guard\StruttonTechnologies.Core.ToolKit.TestingKit.Guard.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Guard\GuardCondition\Behaviors\ValidationBehaviors\" />
  </ItemGroup>
</Project>
