version: 2
updates:
  # Keep NuGet dependencies updated
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "ShawnStrutton"

  # Keep GitHub Actions updated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "ci"
    reviewers:
      - "ShawnStrutton"
