<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>StruttonTechnologies.Core.ToolKit.TestingKit.Assertions</PackageId>
    <Title>StruttonTechnologies Core ToolKit TestingKit Assertions</Title>
    <Description>Reusable assertion helpers for tests.</Description>
    <PackageTags>testing,toolkit,assertions,xunit,strutton,StruttonTechnologies</PackageTags>

    <!-- Versioning -->
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>

    <!-- Packaging -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

</Project>
